const { Client } = require('pg');

const foodItems = [
  {
    id: 'schezwan-shawarma',
    name: 'Schezwan Shawarma',
    category: 'Shawarmas',
    price: 140,
    description: 'Spicy chicken shawarma with Schezwan sauce, fresh vegetables and special garlic mayonnaise wrapped in soft rumali roti.',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'non-veg',
    badge: 'Chef Special 🔥',
    spicy_level: 3,
    prep_time_minutes: 10,
    rating: 4.9,
    ingredients: ['Grilled Chicken Breast', 'Fiery Schezwan Glaze', 'Garlic Toum Mayo', 'Pickled Cucumber', 'Crisp Iceberg Lettuce', 'Fresh Rumali Roti'],
    calories: '420 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-cheese', name: 'Extra Cheese', price: 20 },
      { id: 'extra-chicken', name: 'Extra Chicken', price: 30 },
      { id: 'extra-schezwan', name: 'Extra Schezwan Sauce', price: 15 },
      { id: 'extra-garlic-toum', name: 'Garlic Toum Dip', price: 15 },
    ]),
  },
  {
    id: 'classic-shawarma',
    name: 'Classic Shawarma',
    category: 'Shawarmas',
    price: 120,
    description: 'Traditional Lebanese slow-roasted shredded chicken with authentic garlic toum, french fries and tangy pickled veggies.',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'non-veg',
    badge: 'All-Time Favorite',
    spicy_level: 1,
    prep_time_minutes: 8,
    rating: 4.8,
    ingredients: ['Marinated Rotisserie Chicken', 'Signature Garlic Toum', 'Crispy Fries', 'Tahini Glaze', 'Pickles', 'Soft Pita/Rumali'],
    calories: '380 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-cheese', name: 'Extra Cheese', price: 20 },
      { id: 'extra-chicken', name: 'Extra Chicken', price: 30 },
      { id: 'extra-garlic-toum', name: 'Garlic Toum Dip', price: 15 },
    ]),
  },
  {
    id: 'peri-peri-shawarma',
    name: 'Peri Peri Shawarma',
    category: 'Shawarmas',
    price: 140,
    description: 'Zesty African bird’s eye peri-peri seasoned chicken paired with creamy herb garlic sauce and crunchy peppers.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'non-veg',
    badge: 'Popular',
    spicy_level: 2,
    prep_time_minutes: 10,
    rating: 4.7,
    ingredients: ['Peri Peri Spiced Chicken', 'Creamy Herb Mayo', 'Bell Peppers', 'Pickled Gherkins', 'Warm Flatbread'],
    calories: '410 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-cheese', name: 'Extra Cheese', price: 20 },
      { id: 'extra-chicken', name: 'Extra Chicken', price: 30 },
      { id: 'jalapeno-pickles', name: 'Jalapeños & Arabian Pickles', price: 15 },
    ]),
  },
  {
    id: 'cheese-shawarma',
    name: 'Cheese Shawarma',
    category: 'Shawarmas',
    price: 150,
    description: 'Double cheese indulgence packed with molten mozzarella, rich cheddar blend, and succulent spiced chicken strips.',
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'non-veg',
    badge: 'Cheese Loaded 🧀',
    spicy_level: 1,
    prep_time_minutes: 12,
    rating: 4.9,
    ingredients: ['Spiced Chicken', 'Molten Mozzarella', 'Cheddar Sauce', 'Garlic Mayo', 'Crispy Onions'],
    calories: '490 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-cheese', name: 'Extra Cheese (Triple Loaded)', price: 20 },
      { id: 'extra-chicken', name: 'Extra Chicken', price: 30 },
      { id: 'french-fries-inside', name: 'Fries Loaded Inside', price: 20 },
    ]),
  },
  {
    id: 'bbq-shawarma',
    name: 'BBQ Shawarma',
    category: 'Shawarmas',
    price: 150,
    description: 'Smoky sweet hickory barbecue glazed chicken with caramelized onions, crunchy cabbage, and melted cheese.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'non-veg',
    badge: 'Smoky Rich',
    spicy_level: 1,
    prep_time_minutes: 10,
    rating: 4.8,
    ingredients: ['Smoked BBQ Chicken', 'Hickory BBQ Glaze', 'Caramelized Onions', 'Garlic Sauce', 'Crisp Greens'],
    calories: '440 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-cheese', name: 'Extra Cheese', price: 20 },
      { id: 'extra-chicken', name: 'Extra Chicken', price: 30 },
    ]),
  },
  {
    id: 'mexican-shawarma',
    name: 'Mexican Shawarma',
    category: 'Shawarmas',
    price: 150,
    description: 'Fusion style wrap with Mexican salsa, jalapenos, crunchy tortilla crumbs, chipotle cream, and juicy grilled chicken.',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'non-veg',
    badge: 'Crunchy Fusion',
    spicy_level: 2,
    prep_time_minutes: 10,
    rating: 4.7,
    ingredients: ['Chipotle Chicken', 'Mexican Salsa', 'Sliced Jalapenos', 'Tortilla Chips Crunch', 'Cheese Sauce'],
    calories: '460 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-cheese', name: 'Extra Cheese', price: 20 },
      { id: 'jalapeno-pickles', name: 'Extra Jalapeños', price: 15 },
      { id: 'extra-chicken', name: 'Extra Chicken', price: 30 },
    ]),
  },
  {
    id: 'arabic-plate',
    name: 'Arabic Plate',
    category: 'Plates',
    price: 180,
    description: 'The royal open platter: cut rumali rolls, double portion juicy chicken meat, creamy toum garlic paste, crunchy french fries and fresh pickles.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'non-veg',
    badge: 'Bestseller Platter ⭐',
    spicy_level: 1,
    prep_time_minutes: 12,
    rating: 5.0,
    ingredients: ['200g Grilled Chicken', '2 Cut Rumali Rotis', 'Large Garlic Toum', 'Golden Fries', 'Beetroot & Cucumber Pickles'],
    calories: '580 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-cheese', name: 'Melted Cheese on Plate', price: 20 },
      { id: 'extra-chicken', name: 'Extra Meat Portion (80g)', price: 40 },
      { id: 'extra-garlic-toum', name: 'Extra Toum Bowl', price: 15 },
    ]),
  },
  {
    id: 'shawarma-rice-plate',
    name: 'Shawarma Rice Plate',
    category: 'Rice Items',
    price: 160,
    description: 'Long grain fragrant saffron basmati rice loaded with spiced rotisserie chicken chunks, white garlic sauce and hot harissa drizzle.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'non-veg',
    badge: 'Hearty Meal',
    spicy_level: 2,
    prep_time_minutes: 10,
    rating: 4.8,
    ingredients: ['Saffron Spiced Basmati Rice', 'Charred Chicken Chunks', 'Famous White Sauce', 'Harissa Sauce', 'Toasted Pita Chips'],
    calories: '530 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-chicken', name: 'Extra Chicken Topping', price: 35 },
      { id: 'extra-cheese', name: 'Cheese Drizzle', price: 20 },
      { id: 'extra-schezwan', name: 'Harissa/Schezwan Kick', price: 15 },
    ]),
  },
  {
    id: 'shawarma-salad',
    name: 'Shawarma Salad',
    category: 'Plates',
    price: 120,
    description: 'Healthy & high-protein: Tender grilled chicken slices on a bed of fresh iceberg lettuce, diced tomatoes, black olives, cucumber, and olive oil garlic dressing.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'non-veg',
    badge: 'High Protein / Low Carb',
    spicy_level: 1,
    prep_time_minutes: 8,
    rating: 4.7,
    ingredients: ['150g Lean Grilled Chicken', 'Crisp Iceberg Lettuce', 'Cherry Tomatoes', 'Black Kalamata Olives', 'Lemon Garlic Vinaigrette'],
    calories: '290 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-chicken', name: 'Extra Chicken (+50g)', price: 30 },
      { id: 'extra-cheese', name: 'Feta/Cheddar Cubes', price: 20 },
    ]),
  },
  {
    id: 'paneer-tikka-shawarma',
    name: 'Paneer Tikka Shawarma',
    category: 'Shawarmas',
    price: 130,
    description: 'Char-grilled cottage cheese cubes marinated in aromatic Arabian tandoori herbs, mint toum, crunchy onions, and capsicum.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'veg',
    badge: 'Veg Special 🥬',
    spicy_level: 2,
    prep_time_minutes: 10,
    rating: 4.7,
    ingredients: ['Fresh Malai Paneer', 'Mint & Garlic Sauce', 'Bell Peppers', 'Pickled Onions', 'Rumali Roti'],
    calories: '390 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-cheese', name: 'Extra Mozzarella Cheese', price: 20 },
      { id: 'extra-schezwan', name: 'Schezwan Tossed Paneer', price: 15 },
    ]),
  },
  {
    id: 'falafel-hummus-roll',
    name: 'Falafel Roll with Hummus',
    category: 'Starters',
    price: 110,
    description: 'Golden crispy chickpea falafel patties wrapped with authentic stone-ground tahini hummus, pickles and fresh parsley.',
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'veg',
    badge: 'Authentic Vegan',
    spicy_level: 1,
    prep_time_minutes: 8,
    rating: 4.6,
    ingredients: ['Crispy Spiced Falafel', 'Velvety Chickpea Hummus', 'Tahini Sauce', 'Sumac Onions', 'Pickles'],
    calories: '340 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-cheese', name: 'Add Cheese', price: 20 },
      { id: 'jalapeno-pickles', name: 'Extra Pickles & Jalapenos', price: 15 },
    ]),
  },
  {
    id: 'loaded-chicken-fries',
    name: 'Loaded Chicken Fries',
    category: 'Starters',
    price: 140,
    description: 'Crisp golden french fries loaded with pulled spiced shawarma chicken, jalapeños, melted cheddar and smoked garlic drizzle.',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'non-veg',
    badge: 'Snack Hit',
    spicy_level: 2,
    prep_time_minutes: 10,
    rating: 4.9,
    ingredients: ['Crispy Salted Fries', 'Shredded Chicken', 'Warm Cheddar Sauce', 'Pickled Jalapenos', 'Arabian Spice Dust'],
    calories: '480 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-cheese', name: 'Extra Cheese Fondue', price: 20 },
      { id: 'extra-chicken', name: 'Extra Chicken Layer', price: 30 },
    ]),
  },
  {
    id: 'arabian-mint-mojito',
    name: 'Arabian Mint Mojito',
    category: 'Drinks',
    price: 70,
    description: 'Refreshing crushed fresh garden mint, zesty lime wedges, natural cane sweetness and chilled sparkling soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'veg',
    badge: 'Cooler 🍹',
    spicy_level: 0,
    prep_time_minutes: 4,
    rating: 4.8,
    ingredients: ['Fresh Mint Leaves', 'Key Lime Juice', 'Sparkling Soda', 'Ice Crushed', 'Arabian Rose/Mint Syrup'],
    calories: '110 kcal',
    add_ons: JSON.stringify([]),
  },
  {
    id: 'blue-curacao-blast',
    name: 'Blue Curacao Blast',
    category: 'Drinks',
    price: 80,
    description: 'Vibrant exotic citrus cooler with a dash of tangy lemon and chilled bubbly soda for the perfect shawarma pairing.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'veg',
    badge: 'Chilled',
    spicy_level: 0,
    prep_time_minutes: 4,
    rating: 4.7,
    ingredients: ['Blue Citrus Syrup', 'Lime Juice', 'Soda', 'Mint Sprig', 'Ice'],
    calories: '130 kcal',
    add_ons: JSON.stringify([]),
  },
  {
    id: 'royal-shawarma-combo',
    name: 'Royal Shawarma Combo',
    category: 'Combos',
    price: 240,
    description: 'Complete feast: 1 Jumbo Cheese Shawarma + 1 Peri Peri Loaded Fries + 1 Arabian Mint Mojito drink.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    available: true,
    type: 'non-veg',
    badge: 'Save ₹40 Combo 🎉',
    spicy_level: 2,
    prep_time_minutes: 14,
    rating: 5.0,
    ingredients: ['1x Jumbo Cheese Shawarma', '1x Seasoned Fries Portion', '1x 350ml Mint Mojito', 'Garlic Toum Dip'],
    calories: '760 kcal',
    add_ons: JSON.stringify([
      { id: 'extra-chicken', name: 'Upgrade to Monster Meat', price: 30 },
      { id: 'extra-cheese', name: 'Extra Cheese on Shawarma & Fries', price: 30 },
    ]),
  },
];

async function seed() {
  const client = new Client({
    connectionString: 'postgresql://postgres:Raghul%402008%21@db.xctjbhnwefgcwlnbqoxh.supabase.co:5432/postgres',
    ssl: { rejectUnauthorized: false }
  });

  try {
    await client.connect();
    console.log('Seeding food_items table...');

    for (const item of foodItems) {
      await client.query(`
        INSERT INTO public.food_items (
          id, name, category, price, description, image, available, type, badge,
          spicy_level, prep_time_minutes, rating, ingredients, calories, add_ons
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
        ) ON CONFLICT (id) DO UPDATE SET
          name = EXCLUDED.name,
          category = EXCLUDED.category,
          price = EXCLUDED.price,
          description = EXCLUDED.description,
          image = EXCLUDED.image,
          available = EXCLUDED.available,
          type = EXCLUDED.type,
          badge = EXCLUDED.badge,
          spicy_level = EXCLUDED.spicy_level,
          prep_time_minutes = EXCLUDED.prep_time_minutes,
          rating = EXCLUDED.rating,
          ingredients = EXCLUDED.ingredients,
          calories = EXCLUDED.calories,
          add_ons = EXCLUDED.add_ons;
      `, [
        item.id, item.name, item.category, item.price, item.description, item.image,
        item.available, item.type, item.badge, item.spicy_level, item.prep_time_minutes,
        item.rating, item.ingredients, item.calories, item.add_ons
      ]);
    }

    console.log('FOOD_DATA_SEEDED_SUCCESSFULLY');
    await client.end();
  } catch (err) {
    console.error('SEED_FAILED:', err);
    process.exit(1);
  }
}

seed();
